export const MY_PAGE_MAIN = "MyInfoMain"
export const MY_CREATED_QUIZ = "MyCreatedQuizzes"
export const MY_TRY_QUIZ = "MyTryQuizzes"
export const MY_CHECK_HINT_QUIZ = "MyCheckHintQuizzes"
export const MY_LIKED_QUIZ = "MyLikedQuizzes"
export const MY_SOLVED_QUIZ = "MySolvedQuizzes"